use_frameworks!

target 'login_swift_Example' do
  pod 'login_swift', :path => '../'

  target 'login_swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
